version: '2'

services:
  db:
    environment:
      POSTGRES_DB: ${POSTGRES_PRODUCTION_DB}
      POSTGRES_USER: ${POSTGRES_PRODUCTION_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PRODUCTION_PASSWORD}
    image: ${PRODUCTION_IMAGE_DATABASE}
    networks: ['backend']
    ports: ['5432:5432']
    restart: 'always'
    volumes: ['data-db:/var/lib/postgresql/']
  nginx:
    depends_on: ['php']
    image: ${PRODUCTION_IMAGE_NGINX}
    networks: ['frontend', 'backend']
    ports: ['80:80']
    restart: 'always'
  php:
    depends_on: ['db']
    image: ${PRODUCTION_IMAGE}
    networks: ['backend']
    restart: 'always'
    volumes: ['./.env:/var/www/bicing-api/.env', './var:/var/www/bicing-api/var']

volumes:
  data-db:

networks:
  frontend:
  backend:
